services:
  devcontainer:
    user: root
    image: mcr.microsoft.com/devcontainers/typescript-node
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    working_dir: /workspaces/${localWorkspaceFolderBasename}
    environment:
      C_PORT: ${C_PORT}
      MONGODB_URI: ${MONGODB_URI}
      S_PORT: ${S_PORT}
      SERVER_URI: localhost:${S_PORT}
    depends_on:
      - client
      - server

  client:
    user: root
    image: node:24
    working_dir: /workspaces/${localWorkspaceFolderBasename}
    volumes:
      - ../..:/workspaces:cached
    # Your script should run Vite with --host and the correct port
    command: sh -lc "npm install && npm run client"
    # Bind to host loopback only (not exposed to LAN)
    ports:
      - "127.0.0.1:${C_PORT}:${C_PORT}"
    environment:
      C_PORT: ${C_PORT}
      SERVER_URI: localhost:${S_PORT}
    restart: unless-stopped

  server:
    user: root
    image: node:24
    working_dir: /workspaces/${localWorkspaceFolderBasename}
    volumes:
      - ../..:/workspaces:cached
    command: sh -lc "npm install && npm run server"
    # Bind to host loopback only (not exposed to LAN)
    ports:
      - "127.0.0.1:${S_PORT}:${S_PORT}"
    environment:
      # App connects to Mongo via Docker DNS, not localhost
      MONGODB_URI: ${MONGODB_URI}
      S_PORT: ${S_PORT}
    restart: unless-stopped
    