services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    working_dir: /workspaces/${localWorkspaceFolderBasename}
    environment:
      C_PORT: ${C_PORT}
      MONGODB_URI: ${MONGODB_URI}
      S_PORT: ${S_PORT}
      SERVER_URI: localhost:${S_PORT}
    depends_on:
      - client
      - server

  client:
    image: node:24
    working_dir: /workspaces/${localWorkspaceFolderBasename}/client
    volumes:
      - ../..:/workspaces:cached
      - client-node-modules:/workspaces/${localWorkspaceFolderBasename}/client/node_modules
    # Your script should run Vite with --host and the correct port
    command: sh -lc "npm ci && npm run dev"
    # Bind to host loopback only (not exposed to LAN)
    ports:
      - "127.0.0.1:${C_PORT}:${C_PORT}"
    environment:
      C_PORT: ${C_PORT}
      SERVER_URI: localhost:${S_PORT}
    restart: unless-stopped

  server:
    image: node:24
    working_dir: /workspaces/${localWorkspaceFolderBasename}/server
    volumes:
      - ../..:/workspaces:cached
      - server-node-modules:/workspaces/${localWorkspaceFolderBasename}/server/node_modules
    command: sh -lc "npm ci && npm run dev"
    # Bind to host loopback only (not exposed to LAN)
    ports:
      - "127.0.0.1:${S_PORT}:${S_PORT}"
    environment:
      # App connects to Mongo via Docker DNS, not localhost
      MONGODB_URI: ${MONGODB_URI}
      S_PORT: ${S_PORT}
    restart: unless-stopped

volumes:
  client-node-modules:
  server-node-modules:
